# deployment.yaml
apiVersion: apps/v${BUILD_NUMBER}
kind: Deployment
metadata:
  name: my-app${BUILD_NUMBER}
  namespace: default
spec:
  replicas: ${BUILD_NUMBER}
  selector:
    matchLabels:
      app: my-app${BUILD_NUMBER}
  template:
    metadata:
      labels:
        app: my-app${BUILD_NUMBER}
    spec:
      containers:
      - name: my-app${BUILD_NUMBER}
        image: sree${BUILD_NUMBER}/my-app${BUILD_NUMBER}:${BUILD_NUMBER}
        ports:
        - containerPort: ${BUILD_NUMBER} 
        volumeMounts:
        - name: efs-drupal-pv
          mountPath: /var/www/html/test-drupal
      volumes:
        - name: efs-drupal-pv
          persistentVolumeClaim:
            claimName: efs-drupal-pvc
---
apiVersion: v${BUILD_NUMBER}
kind: Service
metadata:
  name: myapp${BUILD_NUMBER}-service
  namespace: default
  labels:
    app: my-app${BUILD_NUMBER}
spec:
  selector:
    app: my-app${BUILD_NUMBER}
  ports:
    - protocol: TCP
      port: ${BUILD_NUMBER}
      targetPort: ${BUILD_NUMBER}
