<?php

/**
 * @file
 * Implements hooks provided by the IR General module.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function ir_general_page_attachments_alter(array &$attachments) {
  foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
    if ($attachment[1] == 'system_meta_generator') {
      unset($attachments['#attached']['html_head'][$key]);
    }
  }
  $request = \Drupal::request();
  if ($request->attributes->has('csp_nonce')) {
    $nonce = $request->attributes->get('csp_nonce');
    foreach ($attachments['#attached']['html_head'] as &$item) {
      if (is_array($item) && isset($item[0]) && is_array($item[0]) && isset($item[0]['#tag']) && $item[0]['#tag'] === 'script') {
        $item[0]['#attributes']['nonce'] = $nonce;
      }
    }
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function ir_general_menu_local_tasks_alter(&$local_tasks) {
  if (isset($local_tasks['tabs'][0])) {
    // Removing the "Reset password" tab.
    if (isset($local_tasks['tabs'][0]['user.pass'])) {
      unset($local_tasks['tabs'][0]['user.pass']);
    }

    // Removing the "Create new account" tab.
    if (isset($local_tasks['tabs'][0]['user.register'])) {
      unset($local_tasks['tabs'][0]['user.register']);
    }
  }
}
