# kaniko-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--context=git@github.com:sreep1207/app.git"
        - "--destination=sreep1207/test:${COMMIT_ID}"
        - "--cache=true"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      restartPolicy: Never
      volumes:
      - name: workspace
        emptyDir: {}
      imagePullSecrets:
      - name: dockerhub-secret
