_core:
  default_config_hash: OJp9f1IMc5N7ngNsJdtX38fwYinrurpINx58xvmr72o
general_settings:
  client_id: ''
  client_secret: ''
  redirect_uri: ''
  cron_interval: 0
  chunk_to_fetch: 1000
  cache_length: 0
  queue_time: 600
  end_date: yesterday
  start_date: '14 August 2015'
  custom_start_date: ''
  custom_end_date: ''
  custom_start_day: ''
  custom_end_day: ''
  project_name: ''
  profile_id: ''
  gac_type_page: null
  ga4_property_id: '406729972'
  credentials_json_path: ../../innoraft-d414ad30f0ac.json
  node_last_x_days: null
  node_not_newer_than_x_days: null
  node_last_x_nid: null
  metric: screenPageViews
  dimension: pagePath
  result_processor: url_alias
  gac_type_article: null
  gac_type_blog: 1
  gac_type_events: null
  gac_type_landing_page: null
  gac_type_news: null
  gac_type_service: null
  gac_type_remove_storage: 0
